// Scroll-world film configuration — Karim Lazaar's five floating islands.
// Sections 0–3 carry the travel legs (each clip opens ON its island and flies
// to the next, landing exactly on the next section's poster still, so every
// seam is frame-anchored). Section 4 is a "living still": the film rests on
// the observatory while the CTA holds.

export const PALETTE = {
  bg: "#15132B",
  ink: "#F2EFFA",
  inkSoft: "#9A93B8",
  violet: "#8B7CF6",
  teal: "#4FD1C5",
  amber: "#F0A860",
  rose: "#E38FB8",
  sky: "#86AFF5",
};

export const WORLD_CONFIG = {
  brand: null as null,          // site header is rendered by React, not the engine
  nav: false,
  hint: "scroll to fly through",
  atmosphere: true,
  diveScroll: 1.4,
  connScroll: 0.9,
  crossfade: 0.09,
  copyPeak: 0.36,
  sections: [
    {
      id: "studio",
      label: "The Studio",
      still: "/world/still_0.webp",
      clip: "/world/leg_0.mp4",
      clipMobile: "/world/leg_0-m.mp4",
      accent: PALETTE.violet,
      scroll: 1.55,
      ease: "dwell",
      linger: 0.85,
      eyebrow: "Karim Lazaar — Berlin",
      title: "Welcome to my world.",
      body: "I design and build premium digital products where engineering reliability meets cinematic motion.",
      tags: ["Design engineer", "3D & motion", "Product builder"],
    },
    {
      id: "control",
      label: "Control Room",
      still: "/world/still_1.webp",
      clip: "/world/leg_1.mp4",
      clipMobile: "/world/leg_1-m.mp4",
      accent: PALETTE.teal,
      scroll: 1.45,
      ease: "dwell",
      linger: 0.85,
      eyebrow: "Where I come from",
      title: "Broadcast taught me reliability.",
      body: "Years around live TV control rooms — where interfaces cannot fail on air — shaped how I build software: calm, precise, dependable.",
      tags: ["Broadcast ops", "Mission-critical UI"],
    },
    {
      id: "foundry",
      label: "The Foundry",
      still: "/world/still_2.webp",
      clip: "/world/leg_2.mp4",
      clipMobile: "/world/leg_2-m.mp4",
      accent: PALETTE.amber,
      scroll: 1.75,
      ease: "dwell",
      linger: 0.85,
      eyebrow: "What I ship",
      title: "Products, built end to end.",
      body: "From a broadcast-industry platform to football lineup tools and contactless ordering — I take ideas from first sketch to production.",
      tags: ["MediaLinkPro", "Tachkila", "QR Ordering"],
    },
    {
      id: "library",
      label: "The Library",
      still: "/world/still_3.webp",
      clip: "/world/leg_3.mp4",
      clipMobile: "/world/leg_3-m.mp4",
      accent: PALETTE.rose,
      scroll: 1.5,
      ease: "dwell",
      linger: 0.85,
      eyebrow: "What I write & wonder about",
      title: "A universe of curiosity.",
      body: "The library holds more than build logs — essays on AI futures, quantum ideas, night skies, robots, and the strange economics of the brain.",
      tags: ["AI", "Quantum", "Astronomy", "Robotics", "Neuro"],
    },
    {
      id: "observatory",
      label: "Observatory",
      still: "/world/still_4.webp",
      clip: null,
      accent: PALETTE.sky,
      scroll: 1.35,
      eyebrow: "What's next",
      title: "Let's build something together.",
      body: "I'm available for freelance product design and engineering. Tell me what you're dreaming about.",
      tags: [],
      cta: {
        primary: { label: "Get in touch", href: "/contact" },
        secondary: { label: "Explore the universe", href: "/articles" },
      },
    },
  ],
  connectors: [] as (string | null)[],
};
